baseURL = "https://marmo.cc/"
locale = "en-us"
title = "marmocc's"
theme = "hugo-coder"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true

[params]
avatarURL = "images/avatar.jpg"
author = "Tommaso De Tommaso"
description = "Portfolio and Blog"
info = "work in progress"
keywords = "blog,developer,c,c#,philosophy,gamedev"
dateFormat = "January 2, 2006"
since = 2026

hideColorSchemeToggle = false
colorScheme = "dark"

[[params.social]]
name = "GitHub"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/marmocc"

[[params.social]]
name = "YouTube"
icon = "fa-brands fa-youtube fa-2x"
weight = 2
url = "https://youtube.com/@marmocc"

[[params.social]]
name = "Email"
icon = "fa fa-solid fa-envelope"
weight = 3
url = "mailto:contact@marmo.cc"

[taxonomies]
category = "categories"
tag = "tags"

[languages.en]
label = "English"

[[languages.en.menu.main]]
name = "Status"
weight = 1
url = "https://status.marmo.cc"

[params.csp]
childsrc = ["'self'"]
fontsrc = ["'self'"]
formaction = ["'self'"]
framesrc = ["'self'"]
imgsrc = ["'self'"]
objectsrc = ["'none'"]
stylesrc = ["'self'", "'unsafe-inline'"]
scriptsrc = ["'self'"]
prefetchsrc = ["'self'"]
connectsrc = ["'self'"]
